SELECT * FROM BATCH_JOB_EXECUTION;
SELECT * FROM BATCH_JOB_EXECUTION_CONTEXT;
SELECT * FROM BATCH_JOB_EXECUTION_PARAMS;
SELECT * FROM BATCH_JOB_INSTANCE;

SELECT * FROM BATCH_STEP_EXECUTION;
SELECT * FROM BATCH_STEP_EXECUTION_CONTEXT;


INSERT INTO EMPLOYEES(ID,AGE,CITY,COMPANY_NAME,DESIGNATION,EMAIL_ID,NAME) VALUES(1,20,'CITY','TEST','IT','testmailspringbatch@gmail.com','User');
INSERT INTO EMPLOYEES(ID,AGE,CITY,COMPANY_NAME,DESIGNATION,EMAIL_ID,NAME) VALUES(2,20,'CITY','TEST','IT','testmailspringbatch@gmail.com','User1');
INSERT INTO EMPLOYEES(ID,AGE,CITY,COMPANY_NAME,DESIGNATION,EMAIL_ID,NAME) VALUES(3,20,'CITY','TEST','IT','testmailspringbatch@gmail.com','User2');
INSERT INTO EMPLOYEES(ID,AGE,CITY,COMPANY_NAME,DESIGNATION,EMAIL_ID,NAME) VALUES(4,20,'CITY','TEST','IT','testmailspringbatch@gmail.com','User3');